name: publish

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: python-setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: mkdocs-setup
        run: pip install mkdocs-material
      
      - name: mkdocs-pre-build
        run: |
          cp mkdocs/nav.yml mkdocs-conf/nav.yml
          cp -R mkdocs/docs mkdocs-conf/docs/doc/
          cd mkdocs-conf
          chmod +x pre-build.sh
          ./pre-build.sh

      - name: mkdocs-build-deploy
        run: |
          cd mkdocs-conf
          mkdocs gh-deploy \
            --ignore-version \
            --strict \
            --force
