name: publish

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [childrepo-event]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: python-setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: mkdocs-setup
        run: pip install mkdocs-material

      - name: mkdocs-build
        run: |
          make build

      - name: mkdocs-build-deploy
        run: |
          cd mkdocs
          mkdocs gh-deploy \
            --ignore-version \
            --strict \
            --force
