name: registry-push

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      OWNER: demetriusmoro-unico
      IMAGE_NAME: poc-mkdocs-dev
      IMAGE_TAG: 1.0.0

    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: envs
        run: |
          echo "IMAGE_URL=$REGISTRY/$OWNER/$IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_ENV

      - name: docker-build-push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE_URL }}
          secrets: GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
