name: registry-push

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: https://ghcr.io
      OWNER: acesso-io
      IMAGE_NAME: poc-mkdocs-dev
      IMAGE_TAG: 1.0.0

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: envs
        run: |
          echo "IMAGE_URL=$REGISTRY/$OWNER/$IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_ENV

      - name: mkdocs-build-deploy
        run: |
          docker build -t $IMAGE_URL .
          docker push $IMAGE_URL
