site_name: MkDocs multi-repo
repo_url: https://github.com/demetriusmoro-unico/demetriusmoro-unico.github.io
edit_uri: "" # disabled - to enable on root repo set as edit/main/demetriusmoro-unico.github.io/docs/
theme:
  name: "material"
  favicon: assets/main/favicon.png
  logo: assets/main/logo.png
  locale: pt
  language: pt
  font:
    text: Comfortaa
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      accent: blue
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Ativar modo escuro
    - media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: blue
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Ativar modo claro
nav:
  - Início: index.md
  - Cheat sheet: cheat-sheet.md

markdown_extensions:
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      linenums: true
